# kguanoluisa, Import opcional de config externa en C: con fallback al properties del proyecto, spring.config.import, 2026-06-08
spring.config.import=optional:file:C:/empresas_config/application.properties

spring.application.name=apiVirtualEmpresa
jwt.secret=MiSuperSecretoSeguro123456789012345678901234567890
jwt.expiration=86400000
server.address=0.0.0.0
#servidor QA
#server.port=8080
#servidor pruebas
server.port=8090
#produccion
#server.port=8453
server.error.whitelabel.enabled=false
spring.main.web-application-type=servlet
spring.main.banner-mode=off
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
spring.datasource.username=informix
spring.datasource.password=info1210
spring.datasource.url=jdbc:informix-sqli://172.16.17.29:1525/conexus:INFORMIXSERVER=ids_serverdesa
spring.jpa.database-platform=org.hibernate.dialect.InformixDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.dialect=apiVirtualEmpresa.apiVirtualEmpresa.config.InformixDialect
spring.jpa.properties.hibernate.type=INFO
spring.jpa.open-in-view=false

# Conexión con la Pasarela de Pagos (CAPTEC)
metodo-pago.api.base-url=http://172.16.17.17:9092/ApiCaptec/
#metodo-pago.api.base-url=http://192.168.17.31:8089/
metodo-pago.api.username=user
metodo-pago.api.password=postman123

